repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: requirements.txt
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: django-tests
        name: Run Django tests
        entry: python manage.py test
        language: system
        pass_filenames: false
        always_run: true
