# Generated by Django 5.1.1 on 2024-10-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("errorlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorstatistics",
            name="captured_images",
            field=models.TextField(blank=True, null=True),
        ),
    ]
