# Generated by Django 5.1.1 on 2024-10-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processlog', '0003_questiontemplate_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontemplate',
            name='master_log',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionTemplate',
        ),
    ]
