# Generated by Django 5.1 on 2024-10-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processlog", "0005_masterlog_question_file_masterlog_template_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterlog",
            name="question_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="data/process_logs/questions/",
            ),
        ),
        migrations.AlterField(
            model_name="masterlog",
            name="template_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="data/process_logs/templates/",
            ),
        ),
    ]
