# Generated by Django 5.1 on 2024-11-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processlog", "0007_remove_masterlog_question_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterloginfo",
            name="document_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="masterloginfo",
            name="document_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="masterloginfo",
            name="page_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
