# Generated by Django 5.1 on 2024-09-20 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("business", models.CharField(blank=True, max_length=50, null=True)),
                ("operation_time", models.CharField(max_length=8)),
                ("total_operations", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="errorlog",
            name="master_error_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="error_entries",
                to="myapp.mastererrorlog",
            ),
        ),
    ]
