# Generated by Django 5.1 on 2024-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_mastererrorlog_errorlog_master_error_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="pastOpeAdjust",
            field=models.TextField(blank=True, null=True),
        ),
    ]
