# Generated by Django 5.1 on 2024-09-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_logentry_pastopeadjust"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="win_urlpath",
            field=models.TextField(blank=True, null=True),
        ),
    ]
