# Generated by Django 5.1 on 2024-09-20 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_user_errorstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorstatistics",
            name="master_error_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="error_statistics",
                to="myapp.mastererrorlog",
            ),
        ),
        migrations.AddField(
            model_name="errorstatistics",
            name="win_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
