# Generated by Django 5.1 on 2024-09-21 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_errorstatistics_master_error_log_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mastererrorlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.user",
            ),
        ),
    ]
